name: Pull Request - Cleanup
concurrency: preview-${{ github.ref }}

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    name: Clean up
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          action: remove
